name: Docker Publish on Repository Events

on:
  pull_request:
    branches: [ "main" ]
    types:
      - "opened"
      - "synchronize"
      - "reopened"
      - "closed"

jobs:
  detect-changed-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Detect changed images
        id: detect_images
        shell: bash
        run: |
          echo "SHA: ${GITHUB_SHA}"
          IMAGES="$(./.github/scripts/get-images.sh --changed)" || exit 1
          echo "IMAGES: ${IMAGES}"
          echo "::set-output name=images::${IMAGES}"
    outputs:
      images: ${{ steps.detect_images.outputs.images }}
  call-build-workflow:
    needs: detect-changed-images
    uses: ./.github/workflows/docker-publish.yml
    with:
      images: ${{ needs.detect-changed-images.outputs.images }}
      push: ${{ github.event.pull_request.merged && github.event.action == 'closed' }}
    if: needs.detect-changed-images.outputs.images != ''