name: Docker Publish on Manual

on:
  workflow_dispatch:
    inputs:
      images:
        type: string
        default: ''
        required: true
        description: a list of image names to be built and published, seperated by comma (empty means ALL)

jobs:
  call-build-workflow:
    uses: ./.github/workflows/docker-publish.yml
    with:
      images: ${{ github.event.inputs.images }}