name: Docker Publish on Repository Events

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  detect-changed-images:
    runs-on: ubuntu-latest
    steps:
      - name: Set fetch depth
        id: set_fetch_depth
        env:
          COMMITS: "${{ toJson(github.event.commits) }}"
        run: |
          declare -i depth
          if [ "${{ github.event_name }}" = 'pull_request' ]; then
            depth=0
          elif [ "${{ github.event_name }}" = 'push' ]; then
            numCommits=$(echo "$COMMITS" | jq '. | length')
            depth=$(("$numCommits"+1))
          fi
          echo "$depth"
          echo "fetch_depth=${depth}" >> "${GITHUB_OUTPUT}"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ steps.set_fetch_depth.outputs.fetch_depth }}
      - name: Detect changed images
        id: detect_images
        shell: bash
        env:
          BEFORE_COMMIT: ${{ github.event.before }}
          AFTER_COMMIT: ${{ github.event.after }}
        run: |
          echo "EVENT: ${GITHUB_EVENT_NAME}"
          echo "SHA: ${GITHUB_SHA}"
          echo "BASE BRANCH: ${GITHUB_BASE_REF}"
          echo "HEAD BRANCH: ${GITHUB_HEAD_REF}"
          echo "BEFORE COMMIT: ${BEFORE_COMMIT}"
          echo "AFTER COMMIT: ${AFTER_COMMIT}"

          IMAGES="$(./.github/scripts/get-images.sh --changed)" || exit 1
          echo "IMAGES: ${IMAGES}"
          echo "images=${IMAGES}" >> "${GITHUB_OUTPUT}"
    outputs:
      images: ${{ steps.detect_images.outputs.images }}
  call-build-workflow:
    needs: detect-changed-images
    uses: ./.github/workflows/docker-publish.yml
    with:
      images: ${{ needs.detect-changed-images.outputs.images }}
      push: ${{ github.event_name == 'push' }}
    if: needs.detect-changed-images.outputs.images != ''