name: Trigger vulnerability scanning
on:
  schedule:
    - cron: '15 8 * * *'
  workflow_dispatch:
    inputs:
      images:
        type: string
        default: ''
        required: true
        description: a list of image names to be scanned, seperated by comma (empty means ALL)

env:
  REGISTRY: ghcr.io

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set image matrix
        id: set-matrix
        run: |
          declare IMAGES
          if [ -z "${{ inputs.images }}" ]; then
            IMAGES="$(./.github/scripts/get-images.sh)" || exit 1
          else
            IMAGES="${{ inputs.images }}"
          fi
          IFS=, IMAGE_ARRAY=(${IMAGES})

          declare -a IMAGE_REFS
          for IMAGE in "${IMAGE_ARRAY[@]}"; do
            VERSION=$(cat "${IMAGE}/VERSION") || true
            if [ -n "${VERSION}" ]; then
              if [[ ${VERSION} =~ ^([[:alnum:]]|[_])([[:alnum:]]|[-_.])*$ ]]
              then
                IMAGE_REFS+=("${IMAGE}:${VERSION}")
              fi
            fi
          done
 
          JSON_IMAGE_REFS=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${IMAGE_REFS[@]}")
          echo "TARGET_MATRIX: ${JSON_IMAGE_REFS}"
          echo "::set-output name=image_refs_matrix::${JSON_IMAGE_REFS}"
        shell: bash
    outputs:
      target_matrix: ${{ steps.set-matrix.outputs.image_refs_matrix }}

  run-scan:
    name: Scan
    needs: build-matrix
    strategy:
      matrix:
        target_ref: ${{ fromJson(needs.build-matrix.outputs.target_matrix) }}
    uses: ./.github/workflows/vulnerability-scan.yml
    with:
      image_ref: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.target_ref }}
 